### ISSUE TITLE
Unchecking Explorable will hide on profile as well

### ISSUE THREAD

**Issue by Circa-III** [neurosnap/listifi#6]
Perhaps this is intended but if you don't copy your URL before leaving the page, it will be difficult to find your list again. Created lists should probably be shown to the user logged in on their profile even if Explorable is unchecked.

For example I might not want my lists on the Explorable page but I would want them being public on my profile.

**Comment by neurosnap** [comment]
Thank you for submitting this issue!  I agree unexplorable lists should still be available to you in the "My Lists" section but I'm currently filtering them out.  I'll get this fixed and deployed asap.

**Comment by neurosnap** [comment]
You should be able to see private lists inside "My Lists," thanks for raising this issue!
